repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear==18.8.0
        -   flake8-builtins==1.4.1
        -   flake8-comprehensions==2.2.0
        -   flake8-tidy-imports==3.0.0
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.4.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.24.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.7.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.730
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.1
    hooks:
    -   id: python-use-type-annotations
